version: "3"
services:
  hotel-db:
    image: postgres
    environment:
      - POSTGRES_USER=hotel
      - POSTGRES_PASSWORD=a1s2d3f4
    ports:
      - "5432:5432"
  hotel:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hotel-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=hotel
      - SPRING_DATASOURCE_PASSWORD=a1s2d3f4
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop